# Generated by Django 3.2.9 on 2021-11-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=10000, null=True)),
                ('name', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
